---
- include_tasks: "install_{{ ansible_os_family }}.yml"

- name: "Add user {{ libvirt__privileged_users }} to libvirt and kvm group"
  user:
    append: yes
    groups: "libvirt,kvm"
    name: "{{ item }}"
  with_items: "{{ libvirt__privileged_users }}"
  when: libvirt__privileged_users is defined

- name: "Start and enable libvirtd"
  service:
    name: libvirtd
    state: restarted
    enabled: yes

- include_tasks: "setup_networks.yml"
  when: libvirt__bridge_interface is defined

- include_tasks: "setup_pools.yml"
  when: libvirt__fs_pools is defined
